### ISSUE TITLE
Error: Could not resolve '../htmlLang-RJGelu8l.js' from www/scripts/htmlLang/htmlLang.js

### ISSUE THREAD

**Issue by gaterking** [sebastian-software/rollup-plugin-rebase#1]
Hi, when I use this pugin, I get the error as:
`Could not resolve '../htmlLang-RJGelu8l.js' from www/scripts/htmlLang/htmlLang.js
Error: Could not resolve '../htmlLang-RJGelu8l.js' from www/scripts/htmlLang/htmlLang.js
    at /Users/seasons/Documents/Workspaces/VIP/VIP.HR.Performance/node_modules/rollup/src/Bundle.js:319:41`
I set relink exclude 
`const exclude = [
    "**/*.js"
];`
my entry index.js import 'htmlLang' and 'htmlLang' import json file.

**Comment by swernerx** [comment]
Closing because being late. Might not be relevant anymore... is it? Then please reopen! Thanks!
