### ISSUE TITLE
Doesn't work with CSS Modules plugins

### ISSUE THREAD

**Issue by n1313** [sebastian-software/rollup-plugin-rebase#13]
Hi,

I am trying to use this plugin together with CSS Modules plugins ([`rollup-plugin-postcss`](https://github.com/egoist/rollup-plugin-postcss) with `modules` option, or [`modular-css-rollup`](https://github.com/tivac/modular-css/tree/master/packages/rollup#readme)), but I receive an `Unknown word` error:

```
[!] (postcss plugin) CssSyntaxError: /path/styles.css:1:1: Unknown word
path/styles.css
CssSyntaxError: /path/styles.css:1:1: Unknown word
    at error (/usr/local/lib/node_modules/rollup/dist/rollup.js:3258:15)
    at /usr/local/lib/node_modules/rollup/dist/rollup.js:20316:17
    at <anonymous>
```

The CSS file in question is very simple:

```css
.container {
  border: 1px solid red;
  background: url('./background.png');
}
```

Both `rollup-plugin-postcss` and `modular-css-rollup` work perfectly if I use them without `rollup-plugin-rebase`, and `rollup-plugin-rebase` works perfectly if I use it without CSS Modules plugins. The error happens only when I use them together.

My rollup.config.js:

```js
import resolve from 'rollup-plugin-node-resolve';
import json from 'rollup-plugin-json';
import babel from 'rollup-plugin-babel';
import postcss from 'rollup-plugin-postcss'
import clear from 'rollup-plugin-clear';
import rebasePlugin from 'rollup-plugin-rebase';

const rebase = rebasePlugin({
  input: './src/index.js',
  outputFolder: './dist'
});

export default {
  input: './src/index.js',
  output: {
    dir: './dist',
    file: 'bundle.js',
    format: 'es'
  },
  plugins: [
    clear({
      targets: ['./dist']
    }),
    resolve({
      jsnext: true,
      main: true,
      browser: true,
    }),
    json(),
    postcss({
      extract: './dist/styles.css'
    }),
    rebase,
    babel({
      exclude: [
        'node_modules/**'
      ]
    })
  ]
}
```

I have also tried changing the order of postcss and rebase plugins, but that didn't change anything.

Could you please provide some guidance on this matter? How can I get CSS Modules to work and also get my image files to be copied to the destination folder?

**Comment by swernerx** [comment]
I am not sure what extracting with postcss plugin is doing here. You could try again with the new version, though. It changed the integration with rollup quite a bit. Maybe it helps. Please reopen if the issue persists.
