### ISSUE TITLE
Imports of assets are in relation to the importer, however they are always copied in relation to the output folder.

### ISSUE THREAD

**Issue by sebinsua** [sebastian-software/rollup-plugin-rebase#15]
Hello fellow Sebastian,

I found a bug.

[Imports of assets are in relation to the importer, however they are always copied in relation to the output folder.](https://github.com/sebastian-software/rollup-plugin-rebase/blob/master/src/index.js#L108-L114)

To be more wordy:

> `files[fileSource]` is set to point towards `path.join(folder, fileTarget)` while `assetId` is set to point towards the same thing but prefixed with `path.dirname(importer)`. That means if the import is within a folder, the import of the asset will be relative to this, while the file will be copied to a folder that is not relative to this.
> 
> For example, I have an image `TestComponent/image.png` that is imported by a `TestComponent/Component.js`. The `assetId` becomes the absolute path of `./TestComponent/${folder}/${hash}.png`, while `files[fileSource]` points towards `${folder}/${hash}.png`.

I've created a reproduction and unit test for you here: https://github.com/sebinsua/rollup-plugin-rebase/tree/fix/asset-location-within-bundle-output-when-importer-is-deep

I believe the change which would have caused this bug happened here: https://github.com/sebastian-software/rollup-plugin-rebase/commit/a29bf4780ea9434752270cecd5209827cdc3f83c

> **NOTE:** One other unrelated thing which didn't work well with my team's coding style, was that by default you `exclude` instead of only `include`ing certain file types. I would try to explicitly include the file extensions you wish to handle, since otherwise imports like `import cssInJsStyles from './blah.styles'` do not get filtered out and cause unexpected build time errors.

**Comment by swernerx** [comment]
Thanks @sebinsua. Interestingly what you report is actually interesting. You proposed change though changes the whole approach of the plugin. It should indeed remove all superfluous folders from the source structure. There is not really a reason for keeping it - at least not for the use case I imagined while developing the plugin. The goal was to move all assets to the top level while updating references inside any JS files to correctly point to the new location and name.

**Comment by swernerx** [comment]
The use case from @slorber seems different. I'll still investigate what happens there.

**Comment by swernerx** [comment]
@slorber are you able to share some small reproduction of this issues. I figure the woff files you are mentioning are references from inside a CSS file, right?

**Comment by swernerx** [comment]
@sebinsua Your test case is valid. It's just that the solution is not what I think is right.

Working on it now.

**Comment by sebinsua** [comment]
Thanks. Yeah, I made an attempt but the solution didn't seem right hence I never PR'd... >_<

**Comment by slorber** [comment]
@swernerx I don't remember exactly what my setup was, I'm not working anymore on this project, but yes I was importing the fonts from a file inside the react styleguide lib I was trying to build

**Comment by sebinsua** [comment]
@swernerx Any luck in solving the problem yet? 

When I looked I couldn't work out what logic Rollup uses to generate the import paths.

**Comment by serwer-WittGruppe** [comment]
Sorry, having too much other things to do right now in my business.

**Comment by swernerx** [comment]
Thanks for your time - can you check whether the current repository version fixes your issue? Thanks a lot!

**Comment by sebinsua** [comment]
@swernerx I actually don't work at the company that wanted to use this anymore, however I have passed on the news to an ex-colleague @Sergiioo who will look into this at some point.

**Comment by serwer-WittGruppe** [comment]
Released v3 of the plugin which should fix all these issues. If there are still problems feel free to open another report.
