### ISSUE TITLE
V2 Paths are wrong

### ISSUE THREAD

**Issue by bdwain** [sebastian-software/rollup-plugin-rebase#17]
I'm having issues upgrading from v1 to v2. I have a sample repo with the issue. https://github.com/bdwain/rebase-plugin-issue. 

Notice that the generated file has `import dog from './foo/bar/dog_eaAFPAkx.jpg';` even though the image is in the same folder as it. The path to the original image should not appear in the generated import statement.

**Comment by swernerx** [comment]
Thanks for your report @bdwain - can you check whether the current repository version fixes your issue? Thanks a lot!

**Comment by serwer-WittGruppe** [comment]
Okay, I'll check this repository out as well. Otherwise it also would be helpful to get a PR which adds exactly what you need.

**Comment by bdwain** [comment]
I can try to look, but it seems like what I'm suggesting should be the default, not some new functionality. My sample project would just be broken with the current version of the library, unless I'm misunderstanding how it is supposed to be used.

**Comment by swernerx** [comment]
I just released v3 which should fix all remaining issues.

**Comment by bdwain** [comment]
cool thanks! is there a summary of what is a breaking change vs what's not anywhere?

**Comment by bdwain** [comment]
got it. thanks!

**Comment by bdwain** [comment]
Hi @swernerx. I think there are still issues. I tried it with https://github.com/bdwain/rebase-plugin-issue (which I updated to use v3), and it still has the same issue.

The generated code has `import dog from 'foo/bar/dog~eaAFPAkx.jpg';` but it should be `import dog from './dog~eaAFPAkx.jpg';`

**Comment by bdwain** [comment]
Sorry @swernerx my mistake. I had forgotten to unlink my local copy of it. It works. Thanks!

**Comment by swernerx** [comment]
Great :)
