### ISSUE TITLE
Asset required path incorrect when using multiple rollup inputs, input file deeper than one folder, and {preserveModules: true}

### ISSUE THREAD

**Issue by bobbybobby** [sebastian-software/rollup-plugin-rebase#19]
I put a demo project here : https://github.com/bobbybobby/rollup-plugin-rebase-bug-demo

In order to reproduce the bug : 

```
yarn install
yarn run build
```

Then inspect the file `dist/client/util/myutil.js`. 
You see that it requires the less file with `require('../../server/assets/util~fjMwjQrM.less')`. 
This required path is wrong : I don't know why it puts a `server` directory in the path. Even if we ingore the `/server` part, the depth seems wrong, it should go three directories up instead of two. Expected path : `../../../assets/util~fjMwjQrM.less`.

**Comment by swernerx** [comment]
Can you check whether this is still an issue in the current version and re-open if so?

**Comment by ethembynkr** [comment]
https://github.com/sebastian-software/rollup-plugin-rebase/issues/56#issuecomment-2428617343
