### ISSUE TITLE
Path must be a string

### ISSUE THREAD

**Issue by jbccollins** [sebastian-software/rollup-plugin-rebase#2]
I get this error no matter what path I choose for the outputFolder.

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1148:7)
    at ReadStream.<anonymous> (/my/project/node_modules/rollup-plugin-relink/lib/index.js:104:47)
    at emitNone (events.js:86:13)
    at ReadStream.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
    at ReadStream.Readable.push (_stream_readable.js:134:10)
    at onread (fs.js:1984:12)
```

Relevant rollup config:

```javascript
var relinkPlugin = require("rollup-plugin-relink");
const outputFolder = './some/folder';
const relink = relinkPlugin({ outputFolder });

  return rollup.rollup({
    ...
    external: relink.isExternal,
    plugins: [
      ...
      relink,
      ...
    ]
    ...
  })
```

**Comment by swernerx** [comment]
Sorry, for being late. The error is thrown out of the path handling in rebase. The plugin is actually pretty simple. Do you still have this issue? Please reopen if so.

**Comment by jbccollins** [comment]
@swernerx I ended up writing my own plugin :/

**Comment by ClassicOldSong** [comment]
Same here, crashes on this plugin handles any of the file includes.

**Comment by jbccollins** [comment]
@ClassicOldSong I'm not sure what your use case is but https://github.com/jbccollins/postcss-twist-url-assets was my solution. Good luck.

**Comment by ClassicOldSong** [comment]
@jbccollins Thanks but I'm working on my own solution now😂
What I'm aiming at is to create a general purposed assets handler which copies all external files to the destination dir but not only images. Not relying on rollup or other bundlers.

**Comment by jbccollins** [comment]
@ClassicOldSong Cool! If you come up with something that you end up publishing I'd be curious to see it.

**Comment by ClassicOldSong** [comment]
@jbccollins It's a part of the scaffold for my new framework, which is not actually released. But you still can take a look at it: https://github.com/ClassicOldSong/ef.js
