### ISSUE TITLE
The variable "root" may not be retrieved from importee.

### ISSUE THREAD

**Issue by solorhyme0109** [sebastian-software/rollup-plugin-rebase#22]
In the hook `resolveId`, if `importer` is undefined and `!filter(importee)` return true, root can not be assigned any more, because after that, the importer is always not undefined.

![image](https://user-images.githubusercontent.com/30361678/58678271-a861f780-8391-11e9-9573-4da28f430900.png)

I swap the position of the blocks above, and it works.

Is that a bug or I use this plugin in incorrect way?

**Comment by swernerx** [comment]
There were some changes to that section of the code recently. I will close this issue for now. If there is still an issue in the situation your described: please re-open. Many thanks!
