### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by sami616** [sebastian-software/rollup-plugin-rebase#23]
Hi i'm trying to install this on my machine (windows) but the install crashes and fails every time

`npm i -D rollup-plugin-rebase`

First error that appears is:

```
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
```

**Comment by swernerx** [comment]
Modules which use "native code" needs the compiler infrastructure. We use this code for fast hashing of assets. Please make sure to correctly install Node Gyp. https://github.com/nodejs/node-gyp#on-windows
