### ISSUE TITLE
wrong assets folder when using with dynamic imports

### ISSUE THREAD

**Issue by johanneswilm** [sebastian-software/rollup-plugin-rebase#24]
When I run this plugin without also using dynamic imports, it works fine. But when I also use dynamic imports, it adds the original source folder to the assetFolder.

Minimal rollup.config.js:

```
import commonjs from 'rollup-plugin-commonjs'
import resolve from 'rollup-plugin-node-resolve'
import rebasePlugin from "rollup-plugin-rebase"

export default [
    {
        input: 'srx/index.js',
        plugins: [
            rebasePlugin({assetFolder: 'assets'}),
            resolve(),
            commonjs()
        ],
        output: // ES module version, for modern browsers
        {
            dir: "dist",
            format: "es",
            sourcemap: true
        }
    }
]
``` 

In `dist/index.js` I get these kinds of import lines:

```
import jats from './srx/assets/ibSCCdiz.csljson';
import the_faseb_journal from './srx/assets/bDTCtcOg.csljson';
...
```

If I replace the dynamic import with a regular import, I get:
```
import jats from './assets/ibSCCdiz.csljson';
import the_faseb_journal from './assets/bDTCtcOg.csljson';
```

And that's also where the files actually are.

**Comment by swernerx** [comment]
Thanks for the report. What exactly do you mean with "dynamic import"? Can you share a minimum example which showcases the issue?

**Comment by johanneswilm** [comment]
The library I am using this for is https://github.com/fiduswriter/citeproc-plus

I have created a branch "dynamic-import". The very last commit of that is what triggers the issue: https://github.com/fiduswriter/citeproc-plus/commit/3301f87de3e261739787e3fdce0830fb9c77180d If I undo that commit, it works again as expected. The rollup.config.js that I pasted above is a smaller and simplified version of the one in the project. I simplified it as much as possible while still preserving the issue.

**Comment by swernerx** [comment]
I figure that's indeed a missing feature. Mainly thought about this for publishing libraries which all rely on static import/exports. We probably have to figure out what Rollup gives us in comparison to the previous usage in your code at the following position: https://github.com/sebastian-software/rollup-plugin-rebase/blob/master/src/index.js#L98

Actually, dynamic imports are probably a pretty new feature for Rollup at all.

**Comment by swernerx** [comment]
If you have some spare time to try a few things out that would be appreciated.

**Comment by johanneswilm** [comment]
Sure, I can try. So we are looking at any change `importee` and `importer`?

**Comment by johanneswilm** [comment]
Hmm, I cannot see any difference. 
Doing `console.log({importee, importer})` there, I get these results:


With dynamic imports:

```js
{ importee:
   '/home/johannes/src/citeproc-plus/src/assets/fFwkPofr.csljson',
  importer:
   '/home/johannes/src/citeproc-plus/src/assets/fFwkPofr.csljson.js' }
```

without dynamic imports
```js
{ importee:
   '/home/johannes/src/citeproc-plus/src/assets/fxZqbeLS.csljson',
  importer:
   '/home/johannes/src/citeproc-plus/src/assets/fxZqbeLS.csljson.js' }

Notice that none of these locations actually exist. There is a folder `/home/johannes/src/citeproc-plus/src/` but inside it the assets folder is imported from another location:

```js
import {styleLocations} from "../build/styles"
```

**Comment by johanneswilm** [comment]
The files are copied to the right place. It's just the links to them that are incorrect.

For example this in `build/styles.js`:

```js
import jats from "./styles/jats.csljson"
```
gets turned into this in the output file:
```js
import jats from './src/assets/ibSCCdiz.csljson';
```

The correct would be:

```js
import jats from './assets/ibSCCdiz.csljson';
```

**Comment by johanneswilm** [comment]
A temporary fix:

set the assetFolder to be one folder higher up by invoking the plugin like this:

```js
rebasePlugin({
  assetFolder: '../assets'
})
```

Now the links will be correct, but the files will be in the wrong place. Correct this by adding the script to your `package.json` file:

```js
"rollup": "rm -rf dist/ assets/ && rollup -c && mv assets dist/",
```

**Comment by johanneswilm** [comment]
@swernerx This may well be a bug in rollup itself. But I'm not familiar with rollup plugins, so I'm probably not the right person to say that for sure.

**Comment by swernerx** [comment]
Sorry for not responding quickly. I made some changes recently to the logic. May I ask you to share a little project where this issue is visible. I am happy to then check what I can do about it. Alternatively you are also able to work on a PR. The test suite is pretty much covering a lot of cases and might be a good hint on whether something else broke by your changes.

Closing for now. Please re-open if you still want to work on this one.
