### ISSUE TITLE
Doesn't work exclude, doesn't work with scss plugin

### ISSUE THREAD

**Issue by edgar0011** [sebastian-software/rollup-plugin-rebase#25]
ignores exclude param (typo in readme exlude...)
not working with scss plugin, despite scss plugin is run prior, rebase plugin manages to make it stop working, no error.

you can see isolated use case here:
https://github.com/edgar0011/coremylib

**Comment by sami616** [comment]
Yes im experiencing this too, needing to exclude `.scss/.css` assets but the option doesnt seem to be working for me.

**Comment by swernerx** [comment]
The exclude support is now fixed in the last version. Please try combining it in such a way that you exclude scss from this plugin.

I fixed the typo you mentioned - thanks!
