### ISSUE TITLE
CSS autoprefix

### ISSUE THREAD

**Issue by sami616** [sebastian-software/rollup-plugin-rebase#28]
Is there anyway to pipe the css through an autoprefixer? I have a “browserslist” property defined in my package.json but the lib doesn’t seem to be respecting it. 

Is there a way to do this? 🤔

**Comment by swernerx** [comment]
I guess I prefer doing auto-prefixing at app-level, not library-level. Never thought about including it, but feel free to create a PR. Thanks!
