### ISSUE TITLE
Python 3 compat

### ISSUE THREAD

**Issue by s5bug** [sebastian-software/rollup-plugin-rebase#35]
This project depends on `metrohash` in some way. I was able to get it to build by using https://github.com/robertklep/node-metrohash/pull/18, but I'm opening an issue just in case something can/should be done to let other users know (especially users that are mostly unfamiliar with NPM like I am).

**Comment by s5bug** [comment]
Noting here that `metrohash` 2.8.0 fixes these issues. I won't be able to test whether the newer metrohash version is pulled into this project any time in the near future, so I'm not going to close the issue right now.

**Comment by wedneyyuri** [comment]
@s5bug asset hash was updated: https://github.com/sebastian-software/asset-hash/issues/12#issuecomment-877068376. There is no python 2 dependency.

**Comment by s5bug** [comment]
Closing this then!
