### ISSUE TITLE
getting unhandled promise rejections

### ISSUE THREAD

**Issue by bdwain** [sebastian-software/rollup-plugin-rebase#6]
I'm getting this when trying to use the rebase plugin

>(node:94607) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Path must be a string. Received undefined
(node:94607) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I think I followed the instructions correctly

```js
const rebasePlugin = require('rollup-plugin-rebase');
const rebase = rebasePlugin({outputFolder: './es/', verbose: true});
```

and then i added rebase to my plugins array and set external to rebase.isExternal. One difference is that I am just exporting an object and running rollup via the CLI, so i never do the bundle.write part.

when this happens, i get no output from rollup

i also think this happens due to the isExternal thing. it happens even when i remove the plugin from the plugins array

**Comment by bdwain** [comment]
Oh i see. I was missing the input option. However, I am getting other errors now

> Error: Could not resolve '../../ktxAPf.jpg' from src/img/foo.jpg

can you post a working example? It seems the one in the readme is missing a lot. I think that would be really helpful.

Thanks!

**Comment by swernerx** [comment]
I am actually not using this standalone but as part of "prepublish" to rebase assets imported from JS.

https://github.com/sebastian-software/prepublish

**Comment by swernerx** [comment]
There is an example usage here in the repository inside the test section.

**Comment by swernerx** [comment]
I just updated the example inside the readme and tested it locally... seems to work for me. If you need further assistance it would be helpful if you could share a minimal setup which you are using.

**Comment by bdwain** [comment]
sure. so i am building a component library, and the entry point is src/foo.js. inside src are a bunch of other folders which foo.js imports and re-exports from. 

When everything gets bundled by rollup, it goes into es/foo.js. This all works fine for the JS, and i ignore css and handle it separately, but the images are causing me issues.

Some of the files import images like `import logo from './logo.svg'` or `import blah from 'img/whatever.png'` (if i want the image in a more global spot instead of in a specific component folder). I would like to have those images copied to es/img and have the import statements changed to `import foo from './img/logo.svg'` because i am using this bundle from webpack in a separate project and webpack needs to know to look for the img folder in the same directory as es/foo.js. 

other tools i've looked at (like rollup-plugin-img or rollup-plugin-url) all change the import to something like `var logo = './img/logo.svg'` which won't help me because i need webpack to actually process the imports. this plugin seemed like it would do that for me, though i haven't gotten it working yet.

here's my rollup config
```js
const babel = require('rollup-plugin-babel');
const includePaths = require('rollup-plugin-includepaths');
const path = require('path');
const rebasePlugin = require('rollup-plugin-rebase');

const rebase = rebasePlugin({outputFolder: './es/', verbose: true, input: './src/js'});

//entry and output are provided by CLI
const config = {
  output: {
    format: 'es'
  },
  external: rebase.isExternal,
  plugins: [
    includePaths({
      paths: ['src/'],
      external: file => {
        if(file.endsWith('prebuilt.js')){
          return true;
        }
        if(file[0] === '/' || file[0] === '.'){
          return false;
        }
        const includedFolders = ['js', 'img', 'src', 'top-level-exports', 'components'];
        return includedFolders.every(f => !file.startsWith(f + '/'));
      }
    }),
    babel({
      exclude: 'node_modules/**',
      plugins: ['external-helpers'],
      extends: path.resolve(__dirname, '.babelrc')
    }),
    rebase
  ]
};

module.exports = config;

```

**Comment by swernerx** [comment]
Maybe you could try to remove hte "includePaths" plugin. I figure it could maybe conflict with the external handling of the rebase plugin. At least this would be a start.

Other than that your setup looks pretty normal and should work well.

**Comment by swernerx** [comment]
The use case you have is pretty much perfect for the plugin use case. It was developed for that exact reason.

**Comment by bdwain** [comment]
i need includepaths because certain files i want ignored by rollup, and i also want to be able to import not relatively, such as `import foo from 'components/blah/blah.js`. do you know of a way to do that that would not conflict?

**Comment by swernerx** [comment]
I don’t know. I just say try it out without. When it’s not failing anymore that would be at least a good initial hint.

**Comment by bdwain** [comment]
oh that did work. i moved the logic from the external function on the include paths plugin to the main external function and then deleted the plugin and it worked. 

However, now i can't import relative to src like before. Still, this is a start. Thanks!

Any idea why includePaths would conflict? It conflicts even if i just leave the plugin without the external function (since i moved the logic for it)

```js
const rebase = rebasePlugin({outputFolder: './es/', verbose: true, input: './src'});

const config = {
  output: {
    format: 'es'
  },
  external: file => {
    if(rebase.isExternal(file)){
      return true;
    }
    if(file.endsWith('prebuilt.js')){
      return true;
    }
    if(file[0] === '/' || file[0] === '.'){
      return false;
    }
    const includedFolders = ['js', 'img', 'src', 'top-level-exports', 'components'];
    return includedFolders.every(f => !file.startsWith(f + '/'));
  },
  plugins: [
    babel({
      exclude: 'node_modules/**',
      plugins: ['external-helpers'],
      extends: path.resolve(__dirname, '.babelrc')
    }),
    rebase
  ]
};
```

**Comment by bdwain** [comment]
also, it would be great if there was an option to turn off file name hashing. since it's building for a library, i feel like it makes more sense to let the app take care of that and to make it easier to browse the files with unhashed names before the app bundle is built.

**Comment by swernerx** [comment]
That's actually a false assumption. As said in the readme, the whole plugin tries to flatten all asset resources into one folder. This is also the reason why it use content hashes in first place: this way it omits any conflicts in same named files in all the different sub directories.

**Comment by bdwain** [comment]
but isn't the point of the output folder to specify where you want assets? If i set my outputFolder to ./es/img', then it puts the images there, but generates an import without the img subfolder.

const rebase = rebasePlugin({outputFolder: './es/img', verbose: true, input: './src/foo.js'}); is what i am using now.

**Comment by swernerx** [comment]
No. The output folder should always be identical to the rollup output folder. That's the way it is designed and thought of. Seems like you have a slightly different use case.

**Comment by swernerx** [comment]
That said, if it's possible to widen the use cases I am fine with that, too. Feel free to send PRs. :)

**Comment by bdwain** [comment]
cool thanks. I'll see if it matters much to put everything in the img subfolder. it't not a big deal.

and yea i see your point on the file hash. but maybe it could append the hash instead of replace the filename with a hash. This way you can recognize what you're looking at while still avoiding conflicts. i'll do a PR for that.

**Comment by bdwain** [comment]
any recommendations for being able to import relative to the src directory? the includepaths plugin solved that. i'm not sure why it conflicts with this

**Comment by bdwain** [comment]
this also seems to conflict with https://github.com/mixmaxhq/rollup-plugin-root-import. it ends up taking files that were imported with a / at the beginning and treating them like the images for some reason.

**Comment by bdwain** [comment]
i was able to get it working with the original plugin by moving the external check to inside that plugin.
