### ISSUE TITLE
OutputFolder option is confusing

### ISSUE THREAD

**Issue by bdwain** [sebastian-software/rollup-plugin-rebase#8]
This kinda branched off of our discussion in #5. I'm a little confused about the purpose of the outputFolder option. It seems to specify the location that assets are written to, but the generated imports ignore it when calculating what the final import path should be, so your only option is to make sure it points to the same location that files are generated to. Otherwise, you may be trying to import './foo.jpg', but foo.jpg could be in the img subfolder (assuming you specified img in your output folder)

Unless I'm misunderstanding something, I think the best options are to either remove the option or to change the way imports are generated to take into account your output folder.

I think it'd be nice to be able to specify an output folder, because if I have a bunch of images, it might make it hard to look through the top level output folder and find my main js file. 

I'd be happy to make a PR to do this if you think it makes sense.

**Comment by bdwain** [comment]
thoughts on this?

**Comment by swernerx** [comment]
I am actually not sure right now. I figure it was an issue that there is no way for rollup plugins to have access to options like `outputFolder`. Therefor I added it again to the local plugin options.

**Comment by swernerx** [comment]
I figure the code is actually assuming that everything is written into a flat folder structure. The whole rollup handling with renaming the reference while simulatanously putting it into the "external" block list is quite tricky.

I am using this plugin exclusivly inside [prepublish](https://github.com/sebastian-software/prepublish) and have no other use case for now. If you work on this... e.g. enhancing the possibilities it would make sense to double-check that it does not break existing behavior required for *prepublish*.

**Comment by bdwain** [comment]
oh it's only needed because rollup does not expose the output folder? 

that makes more sense, but in that case, I think it would be good to have the generated imports match up with the actual file output. Since the plugin is responible for outputting the files and generating the correct imports for them anyway, it may as well generate the correct imports in all scenarios. 

I'll try a PR and verify this does not affect preublish
